### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by PalgamingHD** [albarv340/amoji#2]
I'm trying to run the mod on a server (with other mods) and I'm getting this crash:
`[20.05 21:45:27] [Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'main' due to errors, provided by 'amoji'!
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[customjava17.jar:1.0.1]
[20.05 21:45:27] [Server] Caused byjava.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.command.v2.ClientCommandRegistrationCallback in environment type SERVER
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[20.05 21:45:27] [Server] 	at red.bread.amoji.fabric.AmojiFabric.onInitialize(AmojiFabric.java:10) ~[Amoji-1.0.1+1.20.1+fabric.jar:?]
[20.05 21:45:27] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
[20.05 21:45:27] [Server] 	... more
`

If you want me to run it by its self on a server I can do that too

**Comment by albarv340** [comment]
Perhaps it wasn't clear from the mod description, but the mod is entirely client-sided. It does not work on servers.

**Comment by PalgamingHD** [comment]
Oh I see, so the command stores everything locally?
Well I'd maybe also like to ask if maybe it could be server sided too to for default server emojis and maybe limit external emojis? Anyways really cool mod regardless

**Comment by albarv340** [comment]
Yes, everything is stored locally. Having default server emojis sounds like an interesting idea, I'll look into it in the future.
